{{- if and (.Values.continuousArchive.enabled) (eq .Values.continuousArchive.storage "pvc") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "spilo.fullname" . }}-archive
  labels: {{ include "spilo.labels" . | nindent 4 }}
  {{- if .Values.continuousArchive.keep }}
  annotations:
    "helm.sh/resource-policy": "keep"
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.continuousArchive.pvc.size }}
  storageClassName: {{ .Values.continuousArchive.pvc.storageClass }}
{{- end }}
